name: Deploy Dev

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: dev
      aws-cluster: freeze-fest-dev
      aws-service: freeze-fest-dev
    secrets: inherit
