name: Guard Main Branch

on:
  pull_request_target:
    branches: [main]

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const labels = (pr.labels || []).map(label => label.name);

            if (!labels.includes('ready-for-prod')) {
              core.setFailed('Add the "ready-for-prod" label before merging into main.');
            }
